home: update bashrc_arch and bash_profile_arch
Bring up to parity with bashrc_ubuntu and bash_profile_ubuntu.

diff --git a/home/bash_profile_arch b/home/bash_profile_arch
--- a/home/bash_profile_arch
+++ b/home/bash_profile_arch
@@ -8,17 +8,29 @@
 # paths and environment variables
 # --------------------------------------------------
 
+# add a directory to the front of PATH if the directory exists
+prepend_path() {
+  if [[ -d "$1" ]] && [[ ":${PATH}:" != *":${1}:"* ]]; then
+    export PATH="${1}${PATH:+":${PATH}"}"
+  fi
+}
+
+# add a directory to the end of PATH if the directory exists
 append_path() {
   if [[ -d "$1" ]] && [[ ":${PATH}:" != *":${1}:"* ]]; then
     export PATH="${PATH:+"${PATH}:"}${1}"
   fi
 }
 
-prepend_path() {
-  if [[ -d "$1" ]] && [[ ":${PATH}:" != *":${1}:"* ]]; then
-    export PATH="${1}${PATH:+":${PATH}"}"
-  fi
-}
+# homebrew
+if [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
+  prepend_path "/home/linuxbrew/.linuxbrew/sbin"
+  prepend_path "/home/linuxbrew/.linuxbrew/bin"
+  export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
+  export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
+  export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
+  export INFOPATH="${INFOPATH+${INFOPATH}:}/home/linuxbrew/.linuxbrew/share/info"
+fi
 
 # local bin
 prepend_path "${HOME}/.local/bin"
@@ -35,6 +47,13 @@ prepend_path "${CABAL_DIR}/bin"
 export CARGO_HOME="${XDG_DATA_HOME}/cargo"
 prepend_path "${CARGO_HOME}/bin"
 
+# dotnet
+export DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=0
+export DOTNET_ROOT="${XDG_DATA_HOME}/dotnet"
+export DOTNET_TOOLS="${DOTNET_HOME}/tools"
+prepend_path "${DOTNET_ROOT}"
+prepend_path "${DOTNET_TOOLS}"
+
 # gcc
 export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
 
@@ -42,25 +61,11 @@ export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quo
 export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
 
 # go
-if [[ -d /usr/local/go/bin ]]; then
-  export GO_BIN=/usr/local/go/bin
-  export GOPATH="${XDG_DATA_HOME}/go"
-  append_path "${GO_BIN}"
-  prepend_path "${GOPATH}/bin"
-fi
+export GOPATH="${XDG_DATA_HOME}/go"
 
 # gpg
 GPG_TTY="$(tty)"
 export GPG_TTY
-
-# homebrew
-if [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
-  append_path "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"
-  export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
-  export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
-  export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
-  export INFOPATH="${INFOPATH+${INFOPATH}:}/home/linuxbrew/.linuxbrew/share/info"
-fi
 
 # less
 export LESSHISTFILE="${XDG_STATE_HOME}/less/history"
@@ -101,7 +106,7 @@ if hash paru &>/dev/null; then
 elif hash yay &>/dev/null; then
   export PACKAGE_MANAGER="yay"
 else
-  echo "No AUR helper detected. Using pacman as the package manager." 1>&2
+  echo "no AUR helper detected" 1>&2
   export PACKAGE_MANAGER="pacman"
 fi
 
@@ -117,8 +122,6 @@ export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
 # stack
 export STACK_ROOT="${XDG_DATA_HOME}/stack"
 prepend_path "${STACK_ROOT}/bin"
-
-unset -f append_path prepend_path
 
 # --------------------------------------------------
 # git functions
@@ -161,7 +164,7 @@ rebase-remote() {
   fi
 
   local current_branch
-  current_branch=$(get-branch-name "$2")
+  current_branch="$(get-branch-name "$2")"
   if [[ -z "${current_branch}" ]]; then
     return 1
   fi
@@ -211,13 +214,9 @@ add-exclude() {
 # add '.vscode*' to .git/info/exclude
 add-exclude-vscode() {
   local repo="${PWD}"
-  if (( $# == 0 )); then
-    echo "error: missing exclude argument" 1>&2
-    echo "usage: add-exclude-vscode <exclude-type>" 1>&2
-    return 1
-  elif (( $# > 1 )); then
+  if (( $# > 1 )); then
     echo "error: too many arguments: $*" 1>&2
-    echo "usage: add-exclude-vscode <exclude-type>" 1>&2
+    echo "usage: add-exclude-vscode [repository]" 1>&2
     return 1
   elif (( $# == 1 )); then
     repo="$1"
@@ -266,12 +265,12 @@ print-path() {
   echo "${PATH//":"/"\n"}"
 }
 
-# find process
+# find a process
 psgrep() {
   pgrep "$@" | xargs --no-run-if-empty ps -fp
 }
 
-# find and kill process
+# find and kill a process
 pskill() {
   local pid
   pid="$(pgrep "$@" | xargs -r ps --no-headers -fp | awk '{ print $2 }')"
@@ -281,11 +280,25 @@ pskill() {
 
 # uncompress files
 extract() {
-  if ! [[ -f "$1" ]]; then
-    echo "not a valid file: '$1'" 1>&2
+  usage() {
+    echo "usage: extract <file>" 1>&2
+    return 1
+  }
+
+  if (( $# == 0 )); then
+    echo "error: missing file argument" 1>&2
+    usage
+  elif (( $# > 1 )); then
+    echo "error: too many arguments: $*" 1>&2
+    usage
+  elif [[ -d "$1" ]]; then
+    echo "error: directory given: $1" 1>&2
+    usage
+  elif ! [[ -f "$1" ]]; then
+    echo "error: file does not exist: $1" 1>&2
     return 1
   elif ! [[ -r "$1" ]]; then
-    echo "file not readable: '$1'" 1>&2
+    echo "error: file not readable: $1" 1>&2
     return 1
   fi
 
@@ -303,7 +316,7 @@ extract() {
     *.Z) uncompress "$1" ;;
     *.7z) 7z x "$1" ;;
     *)
-      echo "unknown compressed file type '.${1#*.}'" 1>&2
+      echo "error: unknown compressed file type '.${1#*.}'" 1>&2
       return 1
       ;;
   esac
@@ -313,7 +326,7 @@ extract() {
 # rc files
 # --------------------------------------------------
 
-[[ -f "${HOME}/.bash_login" ]] && source "${HOME}/.bash_login"
+[[ -r "${HOME}/.bash_login" ]] && source "${HOME}/.bash_login"
 
-[[ -f "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"
+[[ -r "${HOME}/.bashrc" ]] && source "${HOME}/.bashrc"
 
