home: bash_profile: have errors print to stderr instead of stdout

diff --git a/home/bash_profile_arch b/home/bash_profile_arch
--- a/home/bash_profile_arch
+++ b/home/bash_profile_arch
@@ -101,7 +101,7 @@ if hash paru &>/dev/null; then
 elif hash yay &>/dev/null; then
   export PACKAGE_MANAGER="yay"
 else
-  echo "No AUR helper detected. Using pacman as the package manager."
+  echo "No AUR helper detected. Using pacman as the package manager." 1>&2
   export PACKAGE_MANAGER="pacman"
 fi
 
@@ -156,8 +156,8 @@ rebase-at-commit() {
 # rebase a branch on a given remote without having to manually stash any changes
 rebase-remote() {
   if (( $# == 0 )); then
-    echo 'error: need remote name'
-    echo 'usage: rebase-remote <remote> [branch]'
+    echo "error: need remote name" 1>&2
+    echo "usage: rebase-remote <remote> [branch]" 1>&2
   fi
 
   local current_branch
@@ -204,7 +204,7 @@ add-exclude() {
     echo "adding '$1' to '${exclude}'"
     echo "$1" >> "${exclude}"
   else
-    echo "'$1' already exists in '${exclude}'"
+    echo "'$1' already exists in '${exclude}'" 1>&2
   fi
 }
 
@@ -282,10 +282,10 @@ pskill() {
 # uncompress files
 extract() {
   if ! [[ -f "$1" ]]; then
-    echo "not a valid file: '$1'"
+    echo "not a valid file: '$1'" 1>&2
     return 1
   elif ! [[ -r "$1" ]]; then
-    echo "file not readable: '$1'"
+    echo "file not readable: '$1'" 1>&2
     return 1
   fi
 
@@ -303,7 +303,7 @@ extract() {
     *.Z) uncompress "$1" ;;
     *.7z) 7z x "$1" ;;
     *)
-      echo "unknown compressed file type '.${1#*.}'"
+      echo "unknown compressed file type '.${1#*.}'" 1>&2
       return 1
       ;;
   esac
diff --git a/home/bash_profile_ubuntu b/home/bash_profile_ubuntu
--- a/home/bash_profile_ubuntu
+++ b/home/bash_profile_ubuntu
@@ -146,8 +146,8 @@ rebase-at-commit() {
 # rebase a branch on a given remote without having to manually stash any changes
 rebase-remote() {
   if (( $# == 0 )); then
-    echo 'error: need remote name'
-    echo 'usage: rebase-remote <remote> [branch]'
+    echo "error: need remote name" 1>&2
+    echo "usage: rebase-remote <remote> [branch]" 1>&2
   fi
 
   local current_branch
@@ -194,7 +194,7 @@ add-exclude() {
     echo "adding '$1' to '${exclude}'"
     echo "$1" >> "${exclude}"
   else
-    echo "'$1' already exists in '${exclude}'"
+    echo "'$1' already exists in '${exclude}'" 1>&2
   fi
 }
 
@@ -272,10 +272,10 @@ pskill() {
 # uncompress files
 extract() {
   if ! [[ -f "$1" ]]; then
-    echo "not a valid file: '$1'"
+    echo "not a valid file: '$1'" 1>&2
     return 1
   elif ! [[ -r "$1" ]]; then
-    echo "file not readable: '$1'"
+    echo "file not readable: '$1'" 1>&2
     return 1
   fi
 
@@ -293,7 +293,7 @@ extract() {
     *.Z) uncompress "$1" ;;
     *.7z) 7z x "$1" ;;
     *)
-      echo "unknown compressed file type '.${1#*.}'"
+      echo "unknown compressed file type '.${1#*.}'" 1>&2
       return 1
       ;;
   esac
