root: bashrc: remove redundant bash settings

diff --git a/root/bashrc b/root/bashrc
--- a/root/bashrc
+++ b/root/bashrc
@@ -15,40 +15,6 @@ esac
 # --------------------------------------------------
 
 
-# shopt
-#
-shopt -s \
-    autocd cdspell checkhash checkjobs checkwinsize cmdhist dirspell dotglob \
-    expand_aliases extglob extquote globstar histappend interactive_comments \
-    no_empty_cmd_completion progcomp promptvars sourcepath xpg_echo
-if ! shopt -oq posix; then
-    if [ -f /usr/share/bash-completion/bash_completion ]; then
-        source /usr/share/bash-completion/bash_completion
-    elif [ -f /etc/bash_completion ]; then
-        source /etc/bash_completion
-    fi
-fi
-
-# command-not-found
-#
-if [ -x /usr/lib/command-not-found ] \
-    || [ -x /usr/share/command-not-found/command-not-found ]; then
-    command_not_found_handle() {
-        # check because c-n-f could've been removed in the meantime
-        if [ -x /usr/lib/command-not-found ]; then
-            /usr/lib/command-not-found -- "$1"
-            return $?
-        elif [ -x /usr/share/command-not-found/command-not-found ]; then
-            /usr/share/command-not-found/command-not-found -- "$1"
-            return $?
-        else
-            printf "%s: command not found\n" "$1" >&2
-            return 127
-        fi
-    }
-fi
-
-
 # XDG defaults
 #
 [[ -z "$XDG_DATA_HOME" ]] && export XDG_DATA_HOME=~/.local/share
@@ -62,10 +28,10 @@ export CACHE="$XDG_CACHE_HOME"
 
 if [[ -z "$XDG_RUNTIME_DIR" ]]; then
     if pidof "systemd" &>/dev/null; then
-        RUNTIME="/run/user/$UID"
+        export RUNTIME="/run/user/$UID"
     else
-        mkdir --parents /tmp/user/${UID}
-        RUNTIME="/tmp/user/$UID"
+        mkdir --parents "/tmp/user/$UID"
+        export RUNTIME="/tmp/user/$UID"
     fi
     export XDG_RUNTIME_DIR=$RUNTIME
 fi
@@ -80,6 +46,12 @@ export HISTCONTROL=ignoredups
 export HISTIGNORE='history:pwd:ls:ll:la:l:'
 export HISTTIMEFORMAT='%F %T '
 export HISTFILE="$STATE/bash/history"
+
+
+# gpg tty
+#
+GPG_TTY=$(tty)
+export GPG_TTY
 
 
 # Arch settings
@@ -114,168 +86,27 @@ alias wget="wget --hsts-file=\"$DATA/wget-hsts\""
 
 # azure
 #
-export AZURE_CONFIG_DIR="$DATA"/azure
-export AZURE_DEVOPS_CACHE_DIR="$CACHE"/azure-devops
+export AZURE_CONFIG_DIR="$DATA/azure"
+export AZURE_DEVOPS_CACHE_DIR="$CACHE/azure-devops"
 
 
 # npm
 #
-export NPM_CONFIG_USERCONFIG="$CONFIG"/npm/npmrc
+export NPM_CONFIG_USERCONFIG="$CONFIG/npm/npmrc"
 
 
 # gem
 #
-export GEM_SPEC_CACHE="${XDG_CACHE_HOME}"/gem
+export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
+
+
+# pass
+#
+export PASSWORD_STORE_DIR="$DATA/pass"
 
 
 # --------------------------------------------------
-# interactive bash settings
-# --------------------------------------------------
-
-
-# ls
-#
-alias ls='ls -hF --color=auto'
-alias ll='ls -l'
-alias la='ls -Al'
-alias l='ls -C'
-
-
-# mkdir
-#
-alias mkdir='mkdir --parents'
-
-
-# colors
-#
-alias dir='dir --color=auto'
-alias grep='grep --color=auto'
-alias fgrep='fgrep --color=auto'
-alias egrep='egrep --color=auto'
-alias dmesg='dmesg --color'
-
-GCC_COLORS="$(printf "error=01;31:warning=01;35:note=01;%s" \
-    "36:caret=01;32:locus=01:quote=01")"
-export GCC_COLORS
-
-
-# gpg and pass
-#
-GPG_TTY=$(tty)
-export GPG_TTY
-export PASSWORD_STORE_DIR="$DATA"/pass
-
-
-# diff
-#
-alias diffdir='diff -qr'
-
-
-# nvim
-#
-export EDITOR='nvim'
-! which vim &>/dev/null && alias vim='nvim'
-alias {vi,nvi}='nvim'
-alias {vd,nvd,nvimdiff}='nvim -d'
-alias nvim-remove-swap='rm -rf "$XDG_DATA_HOME/nvim/swap/"'
-
-
-# less
-#
-LESS_TERMCAP_mb="$(printf '\E[01;31m')"
-LESS_TERMCAP_md="$(printf '\E[01;38;5;74m')"
-LESS_TERMCAP_me="$(printf '\E[0m')"
-LESS_TERMCAP_se="$(printf '\E[0m')"
-LESS_TERMCAP_so="$(printf '\E[38;5;246m')"
-LESS_TERMCAP_ue="$(printf '\E[0m')"
-LESS_TERMCAP_us="$(printf '\E[04;38;5;146m')"
-
-export LESS_TERMCAP_mb
-export LESS_TERMCAP_md
-export LESS_TERMCAP_me
-export LESS_TERMCAP_se
-export LESS_TERMCAP_so
-export LESS_TERMCAP_ue
-export LESS_TERMCAP_us
-
-export LESSHISTFILE="$CACHE"/less/history
-alias less='less -QR'
-alias man='man -P "less -QR"'
-
-# make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
-
-
-# path
-#
-print-path() {
-    printf "%s\n" "${PATH//:/$'\n'}"
-}
-
-
-# --------------------------------------------------
-# wsl settings
-# --------------------------------------------------
-
-
-# run powershell command
-run-ps() {
-    if [[ $# -eq 0 ]]; then
-        echo "Error: no command provided"
-        echo "Usage: run-ps <command-string>"
-        return 1
-    fi
-
-    pwsh="$(powershell.exe -command "$*" | sed 's/\\/\//g')"
-    echo "${pwsh%$'\r'}"
-}
-
-# get path from windows path
-get-winpath() {
-    if ! [[ $# -eq 1 ]]; then
-        echo "Error: bad arguments: $*"
-        echo "Usage: get-winpath <path>"
-        return 1
-    fi
-
-    winpath="$(wslpath "$1")"
-    echo "${winpath%$'\r'}"
-}
-
-# windows paths
-win_user="$(get-winpath "$(run-ps "echo \"\${env:USERPROFILE}\"")")"
-export win_user
-export win_doc="$win_user/Documents"
-export win_down="$win_user/Downloads"
-
-alias win_user='cd "$win_user"'
-alias win_doc='cd "$win_doc"'
-alias win_down='cd "$win_down"'
-
-# windows 10 x11 forwarding
-winver="$(run-ps "[System.Environment]::OSVersion.Version.Major")"
-if [[ "${winver}" == 10 ]]; then
-    winpath="$(run-ps "echo \"\${env:USERPROFILE}\"")"
-    xauthfile="$win_user/.Xauthority"
-    if [[ -f "$xauthfile" ]]; then
-        touch "$XAUTHORITY"
-        xauth -q merge "$xauthfile"
-        DISPLAY="$(ip route show default | cut -d ' ' -f 3):0"
-        LIBGL_ALWAYS_INDIRECT=0
-        GALLIUM_DRIVER=llvmpipe
-        export DISPLAY
-        export LIBGL_ALWAYS_INDIRECT
-        export GALLIUM_DRIVER
-    fi
-fi
-
-print-path() {
-    printf "%s\n" "${PATH//:/$'\n'}" | grep -v '^/mnt/c/'
-}
-
-
-# --------------------------------------------------
-# binaries
+# path additions
 # --------------------------------------------------
 
 
@@ -292,8 +123,8 @@ fi
 alias {pip,pip3}='python3 -m pip'
 
 pip-update-all() {
-    sudo -H pip list --outdated --format=freeze | grep -v '^\-e' | \
-        cut -d = -f 1 | xargs -n1 sudo -H pip install -U -I
+    pip list --outdated --format=freeze | grep -v '^\-e' | \
+        cut -d = -f 1 | xargs -n1 pip install -U -I
 }
 
 
@@ -375,53 +206,147 @@ fi
 
 
 # --------------------------------------------------
-# other
+# projects
 # --------------------------------------------------
 
 
-# ips and ssh targets
+# local projects
 #
-alias pingpath='mtr'
-alias myip='curl -s checkip.amazonaws.com'
+PROJECTS_DIR="$HOME/projects"
+export PROJECTS_DIR
+
+ASCII_ART="$PROJECTS_DIR/ascii_art"
+[[ -d "$ASCII_ART" ]] && source "$ASCII_ART/ascii.bash"
 
 
-# permissions
+# --------------------------------------------------
+# git settings
+# --------------------------------------------------
+
+
+# git aliases
 #
-alias mx='chmod a+x'
+alias gs='git status'
+alias gf='git fetch'
+alias gfa='git fetch --all'
+alias gp='git pull'
+alias gst='git stash'
+alias ga='git add'
+alias gaa='git add .'
+alias gc='git commit'
+alias gca='git commit --amend'
+alias gb='git branch'
+alias gd='git diff'
+alias gdh='git diff HEAD'
+alias gds='git diff --staged'
+alias gdt='git difftool'
+alias gdth='git difftool HEAD'
+alias gdts='git difftool --staged'
+alias gmt='git mergetool'
+alias git-last-message='git show -s --format=%s'
+alias git-reset-last='git reset HEAD~1'
+alias rebase-origin='rebase-remote origin'
+alias rebase-upstream='rebase-remote upstream'
+alias diff-origin='diff-remote origin'
+alias diff-upstream='diff-remote upstream'
+alias difftool-origin='difftool-remote origin'
+alias difftool-upstream='difftool-remote upstream'
 
 
-# other functions
-#
-psgrep() {
-    pgrep "$@" | xargs --no-run-if-empty ps -fp
-}
-
-pskill() {
-    local pid
-    pid=$(pgrep "$@" | xargs -r ps --no-headers -fp | awk '{ print $2 }')
-    echo "killing $1 (process $pid)..."
-    kill -9 "$pid"
-}
-
-extract() {
-    if [ -f "$1" ]; then
-        case $1 in
-            *.tar.bz2) tar xvjf "$1" ;;
-            *.tar.gz) tar xvzf "$1" ;;
-            *.tar.xz) tar xvf "$1" ;;
-            *.bz2) bunzip2 "$1" ;;
-            *.rar) unrar x "$1" ;;
-            *.gz) gunzip "$1" ;;
-            *.tar) tar xvf "$1" ;;
-            *.tbz2) tar xvjf "$1" ;;
-            *.tgz) tar xvzf "$1" ;;
-            *.zip) unzip "$1" ;;
-            *.Z) uncompress "$1" ;;
-            *.7z) 7z x "$1" ;;
-            *) echo "don't know how to extract '$1'..." ;;
-        esac
-    else
-        echo "'$1' is not a valid file!"
+# print the branch name of the current directory or a given one
+get-branch-name() {
+    local dir=$PWD
+    if [[ -n "$1" ]]; then
+        dir="$1"
     fi
+
+    git -C "$dir" rev-parse --abbrev-ref HEAD
+}
+
+# run an interactive rebase starting at a given commit
+rebase-commit() {
+    if [[ -z "$1" ]]; then
+        echo "error: missing commit-id"
+        echo "usage: update-past-commit <commit-id>"
+        return 1
+    fi
+
+    git rebase --interactive "$1"^
+}
+
+# rebase a branch on a given remote without having to manually stash any changes
+rebase-remote() {
+    if [[ $# -eq 0 ]]; then
+        echo 'error: need remote name'
+        echo 'usage: rebase-remote <remote> [branch]'
+    fi
+
+    local current_branch
+    current_branch=$(get-branch-name "$2")
+    if [[ -z "$current_branch" ]]; then
+        return 1
+    fi
+
+    local branch="master"
+    if [[ $# -gt 1 ]]; then
+        branch="$2"
+    fi
+
+    git fetch --all
+    git rebase "$1/$branch" "$branch"
+
+    if [[ "$current_branch" != "$branch" ]]; then
+        git checkout "$current_branch"
+    fi
+}
+
+# add a line to a repositories .git/info/exclude
+add-exclude() {
+    local repo_config="$PWD"
+    if [[ $# -eq 2 ]]; then
+        repo_config=$2
+    elif [[ $# -ne 1 ]]; then
+        echo "error: bad arguments: '$*'"
+        echo 'usage: add_exclude <exclude-line> [repo-directory]'
+        return 1
+    fi
+
+    repo_config+='/.git/info/exclude'
+    if [[ -z "$repo_config" ]]; then
+        echo "error: repo_config not found: '$repo_config'"
+        return 1
+    fi
+
+    if ! grep -q "^${1}\$" "$repo_config"; then
+        echo "adding '$1' to '$repo_config'"
+        echo "$1" >> "$repo_config"
+    else
+        echo "'$1' already exists in '$repo_config'"
+    fi
+}
+
+# add the hidden .vscode directory to .git/info/exclude
+add-exclude-vscode() {
+    local repo=$PWD
+    if [[ -n "$1" ]]; then
+        repo=$1
+    fi
+    add-exclude '.vscode/' "$repo"
+}
+
+# diff compare against a remote
+diff-remote() {
+    if [[ -z "$1" ]]; then
+        echo "diff-remote <remote> [diff args]"
+    fi
+    git diff "$1/$(get-branch-name)" "${@:2}"
+}
+
+# difftool compare against a remote
+difftool-remote() {
+    if [[ -z "$1" ]]; then
+        echo "difftool-remote <remote> [difftool args]"
+    fi
+    git difftool "$1/$(get-branch-name)" "${@:2}"
 }
 
