bashrc: separate out WSL powershell functions
- added run-ps() and get-wslpath() and replaced any powershell commands
  with them
- renamed some WSL paths and variables

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -226,11 +226,45 @@ alias man='man -P "less -QR"'
 # wsl settings
 #
 if [[ -n "$WSLENV" ]]; then
-    winver="$(powershell.exe \[System.Environment\]::OSVersion.Version.Major)"
+    # run powershell command
+    run-ps() {
+        if [[ $# -eq 0 ]]; then
+            echo "Error: no command provided"
+            echo "Usage: run-ps <command-string>"
+            return 1
+        fi
 
-    if [[ "${winver%$'\r'}" == 10 ]]; then
-        winpath="$(powershell.exe -command "echo \"\${env:USERPROFILE}\"")"
-        xauthfile="$(wslpath "$winpath" | sed 's/[\r]//g')/.Xauthority"
+        pwsh="$(powershell.exe -command "$*" | sed 's/\\/\//g')"
+        echo "${pwsh%$'\r'}"
+    }
+
+    # get path from windows path
+    get-winpath() {
+        if ! [[ $# -eq 1 ]]; then
+            echo "Error: bad arguments: $*"
+            echo "Usage: get-winpath <path>"
+            return 1
+        fi
+
+        winpath="$(wslpath "$1")"
+        echo "${winpath%$'\r'}"
+    }
+
+    # windows paths
+    win_user="$(get-winpath "$(run-ps "echo \"\${env:USERPROFILE}\"")")"
+    export win_user
+    export win_doc="$win_user/Documents"
+    export win_down="$win_user/Downloads"
+
+    alias win_user='cd "$win_user"'
+    alias win_doc='cd "$win_doc"'
+    alias win_down='cd "$win_down"'
+
+    # windows 10 x11 forwarding
+    winver="$(run-ps "[System.Environment]::OSVersion.Version.Major")"
+    if [[ "${winver}" == 10 ]]; then
+        winpath="$(run-ps "echo \"\${env:USERPROFILE}\"")"
+        xauthfile="$win_user/.Xauthority"
         if [[ -f "$xauthfile" ]]; then
             touch "$XAUTHORITY"
             xauth -q merge "$xauthfile"
@@ -242,18 +276,6 @@ if [[ -n "$WSLENV" ]]; then
             export GALLIUM_DRIVER
         fi
     fi
-
-    # windows paths
-    winpath="$(powershell.exe -command "echo \"\${env:USERPROFILE}\"")"
-
-    WIN_USER="$(wslpath "$winpath")"
-    export WIN_USER
-    export WIN_DOC="$WIN_USER/Documents"
-    export WIN_DOWN="$WIN_USER/Downloads"
-
-    alias win_user='cd "$WIN_USER"'
-    alias win_doc='cd "$WIN_DOC"'
-    alias win_down='cd "$WIN_DOWN"'
 
     print-path() {
         printf "%s\n" "${PATH//:/$'\n'}" | grep -v '^/mnt/c/'
