update bashrc and bash.bashrc

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 #
 # ~/.bashrc
 #
@@ -8,9 +10,33 @@ case $- in
     *)   return;;
 esac
 
+
 # term
 TTY=$(tty)
 export GPG_TTY=$TTY
+
+# set variable identifying the chroot you work in (used in the prompt below)
+if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
+    debian_chroot=$(cat /etc/debian_chroot)
+fi
+
+# colored prompt
+if [ -x /usr/bin/tput ] && tput setaf 1 >/dev/null 2>&1; then
+    PS1="$(printf "%s%s" "\${debian_chroot:+(\$debian_chroot)}" \
+        '\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ')"
+else
+    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+fi
+
+# If this is an xterm set the title to user@host:dir
+case "$TERM" in
+    xterm*|rxvt*)
+        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
+        ;;
+    *)
+        ;;
+esac
+
 
 # shell options
 shopt -s checkwinsize
@@ -23,28 +49,45 @@ if ! shopt -oq posix; then
     fi
 fi
 
+# if the command-not-found package is installed, use it
+if [ -x /usr/lib/command-not-found ] || \
+[ -x /usr/share/command-not-found/command-not-found ]; then
+    command_not_found_handle() {
+	    # check because c-n-f could've been removed in the meantime
+        if [ -x /usr/lib/command-not-found ]; then
+            /usr/lib/command-not-found -- "$1"
+            return $?
+        elif [ -x /usr/share/command-not-found/command-not-found ]; then
+            /usr/share/command-not-found/command-not-found -- "$1"
+            return $?
+        else
+            printf "%s: command not found\n" "$1" >&2
+            return 127
+        fi
+    }
+fi
+
+
 # history
 PROMPT_COMMAND="history -a"
 HISTSIZE=1000
 HISTFILESIZE=2000
 
-# rust binaries
-rust_env="$HOME/.cargo/env"
-if [ -f "rust_env" ]; then
-    . "$rust_env"
-fi
 
-# use aliases with sudo and refresh when used
+# refresh sudo and export environment
 alias sudo="sudo -v; sudo --preserve-env "
 
-# ls aliases
+
+# ls
 alias ls="ls -hF --color=auto"
 alias ll="ls -l"
 alias la="ls -Al"
 alias l="ls -C"
 
+
 # mkdir
 alias mkdir="mkdir --parents"
+
 
 # colors
 alias dir="dir --color=auto"
@@ -53,10 +96,17 @@ alias fgrep="fgrep --color=auto"
 alias egrep="egrep --color=auto"
 alias dmesg="dmesg --color"
 
+GCC_COLORS="$(printf "error=01;31:warning=01;35:note=01;%s"\
+    "36:caret=01;32:locus=01:quote=01")"
+export GCC_COLORS
+
+
 # nvim
 export EDITOR="nvim"
 alias {vi,nvi}="nvim"
 alias {nvimdiff,nvd,vd}="nvim -d"
+alias remove_nvim_swap="rm -rf ~/.local/share/nvim/swap/"
+
 
 # less
 LESS_TERMCAP_mb="$(printf '\E[01;31m')"
@@ -78,17 +128,33 @@ export LESS_TERMCAP_us
 alias less='less -Q'
 alias man='man -P "less -Q"'
 
+# make less more friendly for non-text input files, see lesspipe(1)
+[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+
+
+# environments
+fzf_env="$HOME/.fzf.bash"
+[ -f "$fzf_env" ] && . "$fzf_env"
+
+rust_env="$HOME/.cargo/env"
+[ -f "$rust_env" ] && . "$rust_env"
+
+
 # git
-alias gs="git status"
-alias gp="git pull"
-alias gst="git stash"
-alias gd="git diff"
-alias gdt="git difftool"
-alias gf="git fetch --all"
-alias gc="git commit"
-alias gca="git commit --amend"
-alias ga="git add"
-alias gb="git branch"
+alias gs='git status'
+alias gf='git fetch --all'
+alias gp='git pull'
+alias gst='git stash'
+alias ga='git add'
+alias gaa='git add .'
+alias gc='git commit'
+alias gca='git commit --amend'
+alias gb='git branch'
+alias gd='git diff'
+alias gdt='git difftool'
+alias gdh='git diff HEAD'
+alias gdth='git difftool HEAD'
+alias gmt='git mergetool'
 
 get_branch() {
     local branch_name
@@ -97,25 +163,25 @@ get_branch() {
     echo "$branch_name"
 }
 
-update_branch() {
-    local branch_name
-    branch_name=$(get_branch)
-    if [ -z "$branch_name" ]; then
-        return 1
-    fi
-
-    if [ $# -eq 0 ] || [ "$1" = "$branch_name" ]; then
-        git pull
-    else
-        printf "Temporarily checking out %s\n" "$1"
-        git checkout "$1"
-        git pull
-        printf "\nChecking back out %s\n" "$branch_name"
-        git checkout "$branch_name"
-    fi
-}
-
 update_master() {
+    update_branch() {
+        local branch_name
+        branch_name=$(get_branch)
+        if [ -z "$branch_name" ]; then
+            return 1
+        fi
+
+        if [ $# -eq 0 ] || [ "$1" = "$branch_name" ]; then
+            git pull
+        else
+            printf "Temporarily checking out %s\n" "$1"
+            git checkout "$1"
+            git pull
+            printf "\nChecking back out %s\n" "$branch_name"
+            git checkout "$branch_name"
+        fi
+    }
+
     if [ -z "$(get_branch)" ]; then
         return 1
     fi
@@ -156,14 +222,14 @@ update_master() {
     fi
 }
 
-# checkpatch
-alias ckp="./scripts/checkpatch.pl -g"
 
 # ips and ssh targets
-alias myip="curl -s checkip.amazonaws.com"
+alias myip='curl -s checkip.amazonaws.com'
+
 
 # chmod and permissions commands
 alias mx='chmod a+x'
+
 
 # other functions
 psgrep() {
@@ -197,67 +263,4 @@ extract () {
         printf "'%s' is not a valid file!\n" "$1"
     fi
 }
-
-
-
-# Ubuntu
-
-# make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
-
-# set variable identifying the chroot you work in (used in the prompt below)
-if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-    debian_chroot=$(cat /etc/debian_chroot)
-fi
-
-# set a fancy prompt (non-color, unless we know we "want" color)
-case "$TERM" in
-    xterm-color|*-256color) color_prompt=yes;;
-esac
-
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-force_color_prompt=yes
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-        # We have color support; assume it's compliant with Ecma-48
-        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-        # a case would tend to support setf rather than setaf.)
-        color_prompt=yes
-    else
-        color_prompt=
-    fi
-fi
-
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-else
-    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-fi
-unset color_prompt force_color_prompt
-
-# If this is an xterm set the title to user@host:dir
-case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    ;;
-*)
-    ;;
-esac
-
-# enable color support of ls and also add handy aliases
-if [ -x /usr/bin/dircolors ]; then
-    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
-    alias grep='grep --color=auto'
-    alias fgrep='fgrep --color=auto'
-    alias egrep='egrep --color=auto'
-fi
-
-# colored GCC warnings and errors
-export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
-
-# Add an "alert" alias for long running commands.  Use like so:
-#   sleep 10; alert
-alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
 
